# nixpacks.toml

[phases.setup]
nixPkgs = ['...', 'go', 'nodejs', 'npm']

[phases.install]
cmds = ['go mod download', 'npm install --prefix frontend/']

[phases.build]
cmds = ['go build -o out', 'npm run build --prefix frontend/']

[start]
cmd = './out'
